### ISSUE TITLE
warn: Module dresscode-less not found as module

### ISSUE THREAD

**Issue by kenorb** [crazytigershark/doxydoc#2]
```
% npm install -g doxydoc
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest

changed 92 packages, and audited 92 packages in 3s

1 package is looking for funding
  run `npm fund` for details

15 vulnerabilities (7 moderate, 8 high)

% doxydoc
warn: Module dresscode-less not found as module, but could resolve it as local module. It's better to require this module as a local module!
ERR Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/doxydoc/templates/lagoon/dresscode-less.js'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at Object.read (/usr/local/lib/node_modules/doxydoc/node_modules/node-fl/fl.js:165:27)
    at Superjoin.loadFile (/usr/local/lib/node_modules/doxydoc/node_modules/superjoin/modules/superjoin.js:566:43)
    at Superjoin.addModule (/usr/local/lib/node_modules/doxydoc/node_modules/superjoin/modules/superjoin.js:297:27)
    at Superjoin.<anonymous> (/usr/local/lib/node_modules/doxydoc/node_modules/superjoin/modules/superjoin.js:156:22)
    at Array.forEach (<anonymous>)
    at Superjoin.<anonymous> (/usr/local/lib/node_modules/doxydoc/node_modules/superjoin/modules/superjoin.js:155:19)
    at new Promise (<anonymous>)
    at Superjoin.collectTask (/usr/local/lib/node_modules/doxydoc/node_modules/superjoin/modules/superjoin.js:141:23)
```

**Comment by crazytigershark** [comment]
I tried to fix this. Doxydoc needs to be refactored, there are more modules out of date and a couple of modules aren't maintained anymore. I plan to do a complete re-write of Doxydoc. So best for you is to look for another module for now.
